version: '3.9'

services:
  api:
    container_name: api
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./SQL/db/pgdata:/var/lib/postgresql/data
    expose:
      - 5430
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
    driver: bridge
